name: Nascraft
version: $version
main: me.bounser.nascraft.Nascraft
api-version: 1.13
softdepend: [ Vault, PlaceholderAPI, AdvancedGUI, DiscordSRV ]
authors: [ bounser ]
description: Market valuations in minecraft
folia-supported: true

commands:
  migrate:
    description: Migrates data from H2 to Redis
    usage: /migrate
    permission: nascraft.admin